#!/bin/sh


#how to retrieve standard descriptions
#
#lsad=00

#eval string=\$ls_${lsad}
#echo $string

# how to retrieved alternate descriptions
#
#lsad=00
#state=CT
#type=place

#eval string=\$ls_${lsad}_${state}_${type}
#echo $string


# the first batch are the official 1-for-1 mappings from
# http://factfinder2.census.gov/help/en/glossary/l/legal_statistical_area_description_code.htm

ls_00='Nation'
ls_01='State or State equivalent'
ls_03='City and Borough (AK, legal, county equivalent)'
ls_04='Borough (AK, legal, county equivalent)'
ls_05='Census Area (AK, statistical, county equivalent)'
ls_06='County'
ls_07='District (American Samoa, legal, county equivalent)'
ls_08='Independent City (MD, MO, VA, legal, county equivalent)'
ls_09='Independent City (NV, legal, county equivalent)'
ls_10='Island (Virgin Islands, legal, county equivalent, but change may be coming)'
ls_11='Island (American Samoa, legal, county equivalent)'
ls_12='Muncipality (AK, Northern Mariana Islands, legal, county equivalent)'
ls_13='Municipio (Puerto Rico, legal, county equivalent)'
ls_14='(DC, Guam, legal, county equivalent)'
ls_15='Parish (LA, legal, county equivalent)'
ls_19='Reservation (ME, NY, legal, county subdivision)'
ls_20='Barrio (Puerto Rico, legal, county subdivision)'
ls_21='Borough (NY,NJ,PA, legal, county subdivision/subdivision equivalent)'
ls_22='CCD - Census County Division (statistical, county subdivision equivalent)'
ls_23='census subarea (Alaska, statistical, county subdivision equivalent)'
ls_24='subdistrict (Virgin Islands, legal, county subdivision equivalent)'
ls_25='City (legal, county subdivision equivalent)'
ls_26='County (American Samoa, legal, county subdivision equivalent)'
ls_27='District (PA, VA, WV, Guam, Northern Mariana Islands, county subdivision equivalent, election, magisterial, municipal or road district'
ls_28="District (LA, MD, MI, VA, WV, Northern Mariana Islands, County subdivision, assessment, election, magisterial, supervisor's, parish governing authority, or municipal district"
ls_29='precinct (IL, NE, legal, county subdivision, election precinct)'
ls_30='precinct (IL, NE, legal, county subdivision, election precinct)'
ls_31='Gore (ME, VT, legal, county subdivision)'
ls_32='Grant (NH, VT, legal, county subdivsion)'
ls_33='Independent City (MD, MO, VA, legal, county subdivsion equivalent)'
ls_34='Independent City (NV, legal, county subdivsion equivalent)'
ls_35='Island (American Samoa, legal, county subdivision)'
ls_36='Location (NH, legal, county subdivsion)'
ls_38='Arlington County VA (legal, county subdivision equivalent)'
ls_39='Plantation (ME, legal, county subdivision)'
ls_40='Territorial water areas (legal, county subdivision)'
ls_41='Barrio-Pueblo (Puerto Rico, legal, county subdivision)'
ls_42='Purchase (NH, legal, county subdivision)'
ls_43='Town (legal, county subdivision or county subdivision equivalent)'
ls_44='Township (legal, county subdivision)'
ls_45='Township (KS, MN, NE, NC, legal, county subdivision)'
ls_46='UT (statistical, county subdivision equivalent)'
ls_47='Village (NJ, OH, SD, WI, legal, county subdivision equivalent)'
ls_49='Charter Township (MI, legal, county subdivision)'
ls_51='Subbarrio (Puerto Rico, legal, subdivision of Barrio)'
ls_53='City and Burough (AK, legal, incorporated place)'
ls_54='Municipality (AK, legal, incorporated place)'
ls_55='Comunidad (Puerto, statistical, apparently equivalent to CDP)'
ls_56='Borough (CT, NJ, PA, legal, incorporated place)'
ls_57='CDP (Census Designated Place, statistical)'
ls_58='City (49 states (not HI), DC, legal, incorporated place)'
ls_59='Place (KY, MT, NV, TN, legal, incorporated place, CT, GA, IN, MT, TN, quasi-legal, place equivalent)'
ls_60='Town (legal, incorporated place)'
ls_61='Village (legal, incorporated place)'
ls_62='Zona Urbana (Puerto Rico, statistical, place)'
ls_65='City (CT, GA, IN, legal, consolidated city)'
ls_66='Consolidated City (GA, MT, TN, legal)'
ls_68='Region (Census Region)'
ls_69='Division (Census Division)'
ls_71='CMSA (Consolidated Metropolitan Statistical Area)'
ls_72='MSA (Metropolitan Statistical Area)'
ls_73='PMSA (Primary Metropolitan Statistical Area)'
ls_74='NECMA (New England County metropolitan Area)'
ls_75='Urbanized Area'
ls_76='Urban Cluster'
ls_77='Alaska Native (Alaska Native Regional Corporation)'
ls_78='Home Land (Hawaiian home land)'
ls_79='ANVSA (Alaska Native Village statistical Area)'
ls_80='TDSA (Tribal Designated Statistical Area)'
ls_81='Colony (NV, American Indian Reservation)'
ls_82='Community (CA, MN, NV, OR, WI, American Indian Reservation)'
ls_83='Joint Use Area (KS, NM, WI, American Indian Reservation equivalent)'
ls_84='Pueblo (NM, TX, American Indian Reservation)'
ls_85='Rancheria (CA, American Indian Reservation)'
ls_86='Reservation (American Indian Reservation)'
ls_87='Reserve (AK, American Indian Reservation)'
ls_88='OTSA (Oklahoma Tribal Statistical Area)'
ls_89='Trust Land (CA, FL, ME, MA, MN, NE, NV, American Indian Reservation equivalent'
ls_90='Joint Use Area/OTSA (OK, statistical eqvivalent of American Indian Reservation)'
ls_91='Ranch (CA, NV, American Indian Reservation)'
ls_92='SDAISA (AL, DE, LA, NJ, NC, VA, State Designated American Indian Statistical Area)'
ls_93='Indian Village (CA, OR, American Indian Reservation)'
ls_94='Village (American Indian Reservation)'
ls_95='Indian Community (MI, MN, American Indian Reservation)'
ls_C1='Congressional District (state with one district)'
ls_C2='Congressional District (state with two or more districts)'
ls_C3='Resident Commisioner District (Puerto Rico, Congressional district)'
ls_C4='Delegate District (DC, AS, GU, VI, Congressional District)'
ls_CN='Incorporated Place (WV)'
ls_LL='State House District (state legislative district, lower chamber)'
ls_LU='State Senate District (state  legislative district, upper chamber)'
ls_M0='Combined Statistial Area'
ls_M1='Metropolitan Statistical Area'
ls_M2='Micropolitan Statistical Area'
ls_M3='Metropolitan Division'
ls_M4='Combined NECTA (New England City and Town Combined Statistical Area)'
ls_M5='Metropolitan NECTA (New England City and Town Metropolitan Statistical Area)'
ls_M6='Micropolitan NECTA (New England City and Town Micropolitan Statistical Area)'
ls_M7='NECTA Division (New England City and Town Metropolitan Division)'
ls_P1='1% public use microdata area'
ls_P5='5% public use microdata area'
ls_S1='Elementary school district'
ls_S2='Secondary school district'
ls_S3='Unified school district'
ls_S4='Administrative school area in Hawaii and New York City'
ls_S5='Bureau of Indian Affairs school area'
ls_S6='Department of Defense school area'
ls_T1='Area (AZ, MI, UT, WI, American Indian tribal subdivision)'
ls_T2='Chapter (AZ, NM, UT, American Indian tribal subdivision)'
ls_T3='Community (NC, SD, American Indian tribal subdivision)'
ls_T4='District (AZ, MN, MT, NE, ND, SD, American Indian tribal subdivision)'
ls_T5='District (AZ, OK, SD, American Indian tribal subdivision)'
ls_T6='Segment (MN, ND, American Indian tribal subdivision)'
ls_TZ='Traffic analysis zone'
ls_V0='Voting District'
ls_V1='Voting District'
ls_V2='Voting District'
ls_Z3='3 digit ZCTA'
ls_Z5='5 digit ZCTA'

# the second batch are the alternate mappings found in the
# actual files

ls_00_CT_place='City of Milford legal boundary'
ls_00_GA_place='Athens, Macon & Agusta - legal boundary'
ls_UG_GA_place='Unified Government (City & County) - legal boundary'
ls_00_IN_place='Indianaplis - legal boundary'
ls_00_KS_place='Tribune/Greeley County - legal boundary - see consolidated/KS for more inclusive version'
ls_00_KY_place='combined Louisville/Jerferson county metro boundary balance. see TIGER2014/consolidated/KY for a complete boundary'
ls_UC_KY_place='Urban County - Legal boundary'
ls_00_MT_place='Anaconda-Deer Lodge County & Butte-Silver Bow - combined City/County legal boundaries'
ls_00_NJ_place='Princeton - Munincipality, combined Borough and Township'
ls_00_NV_place='Carson City - Independent City, not contained within any County'
ls_00_TN_place='Nashville-Davidson Metro, Hartsville/Trousdale County governments. See consolidated/TN for a more inclusive Nashville-Davidson Metro border'

ls_00_AS_cousub='Rose & Swain Islands'
ls_00_CT_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_GU_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_IL_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_IN_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_MA_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_MI_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_MN_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_MP_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_NC_cousub='Cleveland County (County Subdivisions not defined)'
ls_00_NH_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_NJ_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_NY_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_OH_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_PA_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_PR_cousub='Muncipio Subdivisions not defined (offshore areas, should be 40)'
ls_00_RI_cousub='County Subdivisions not defined (offshore areas, should be 40)'
ls_00_VA_cousub='County Subdivsions not defined (Arlington - former DC)'
ls_00_VI_cousub='Island Subdivisions not defined (offshore areas, should be 40)'
ls_00_WI_cousub='County Subdivisions not defined (offshore areas, should be 40)'
